openapi: 3.0.2
info:
  title: Event Management API
  version: 1.0.0
  description: Event Management API docs
Authorization: Bearer <token>
tags:
  - name: Users
    description: Operations related to users
  - name: Events
    description: Operations related to events
schemes:
  - https
  - http
paths:
  /users:
    post:
      tags:
        - Users
      summary: Register a new user
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: test@test.com
                password: testtest
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              examples:
                User created:
                  value:
                    message: User created
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                User already exists:
                  value:
                    error: User already exists
        "406":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Email or password not acceptable:
                  value:
                    error: Email or password not acceptable
  /sessions:
    post:
      tags:
        - Users
      summary: Login a user
      description: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: test@test.com
                password: testtest
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              examples:
                User created:
                  value:
                    message: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNWFlNzBmNDYyMTFkMGI1NWM1OWYyMiIsImlhdCI6MTY2OTI5ODI0NCwiZXhwIjoxNjY5Mzg0NjQ0fQ.mZQISGvaD03Ps8d_o-S4MHdZ_zwjGmsc-qWGc-zkISc
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong password:
                  value:
                    error: Wrong password
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                User does not exist:
                  value:
                    error: User does not exist
        "411":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Email or password field empty:
                  value:
                    error: Email or password field empty
  /events:
    post:
      tags:
        - Events
      summary: Add a new event
      description: Add a new event
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                image:
                  type: string
                location:
                  type: string
                time:
                  type: date
              example:
                title: Jaanituli
                image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                location: Tartu
                time: "2023-06-23T18:30:00"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
              examples:
                Event created:
                  value:
                    _id: 637f1b7a6758a7e19c0984eb
                    title: Võrkpall
                    image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                    location: Võru
                    time: "2023-05-23T08:30:00.000Z"
                    authorId: 635ae70f46211d0b55c59f22
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                No authorization token was found:
                  value:
                    error: No authorization token was found
        "411":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                One or more required fields empty:
                  value:
                    error: One or more required fields empty
    get:
      tags:
        - Events
      summary: Get a list of all events
      description: Get a list of all events
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                items:
                    $ref: "#components/schemas/Event"
              example:
                  - _id: 635c381cc8c825565c56c291
                    image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                    location: Tallinn
                    time: '2023-12-25T00:00:00.000Z'
                    authorId: 635ae70f46211d0b55c59f22
                  - _id: 635c381cc8c825565c56c291
                    image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                    location: Haapsalu
                    time: '2023-12-25T00:00:00.000Z'
                    authorId: 635ae70f46211d0b55c59f44
          description: Returns a list of Events or an empty array
    put:
      tags:
        - Events
      summary: Edit event
      description: Edit event
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                image:
                  type: string
                location:
                  type: string
                time:
                  type: date
              example:
                id: 637f1b7a6758a7e19c0984eb
                title: Jaanituli
                image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                location: Tartu
                time: "2023-06-23T18:30:00"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                  $ref: "#components/schemas/Event"
              example:
                  _id: 635c381cc8c825565c56c291
                  title: Uus Jaanituli
                  image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                  location: Tartu
                  time: '2023-05-23T08:30:00.000Z'
                  authorId: 635ae70f46211d0b55c59f22
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                One or more required fields empty:
                  value:
                    error: One or more required fields empty
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                No authorization token was found:
                  value:
                    error: No authorization token was found
  /events/own:
    get:
      tags:
        - Events
      summary: Get a list of users events
      description: Get a list of users events
      security:
        - bearerAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                  items:
                    $ref: "#components/schemas/Event"
              example:
                  - _id: 635c381cc8c825565c56c291
                    title: Jaanituli
                    image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                    location: Tallinn
                    time: '2023-12-25T00:00:00.000Z'
                    authorId: 635ae70f46211d0b55c59f22
                  - _id: 635c381cc8c825565c56c291
                    title: Kulutuli
                    image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
                    location: Koeru
                    time: '2023-12-25T00:00:00.000Z'
                    authorId: 635ae70f46211d0b55c59f22
          description: Returns a list of users Events or an empty array
  /events/{id}:
    delete:
      tags:
        - Events
      summary: Delete event
      description: Delete event
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the event that will be deleted
          example: 635c381cc8c825565c56c291
      responses:
        "204":
          description: Retruns status code 204 with no body
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                No authorization token was found:
                  value:
                    error: No authorization token was found
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Event not found:
                  value:
                    error: Event not found
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Event:
      title: Event object
      description: ''
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        image:
          type: string
        location:
          type: string
        time:
          type: date
        authorId:
          type: string
        example:
          _id: 637f1b7a6758a7e19c0984eb
          title: Võrkpall
          image: https://img.freepik.com/free-vector/silhouettes-rock-concert_1048-4815.jpg
          location: Võru
          time: "2023-05-23T08:30:00.000Z"
          authorId: 635ae70f46211d0b55c59f22
    Error:
      title: error object
      description: ''
      type: object
      properties:
        error:
          type: string
      example:
        error: Error message.
    Success:
      title: success object
      description: ''
      type: object
      properties:
        message:
          type: string
      example:
        message: Success message
          
